// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    user_id, api_key_id, analysis_request_id, type, description, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, api_key_id, analysis_request_id, type, description, ip_address, user_agent, created_at
`

type CreateAuditEventParams struct {
	UserID            pgtype.Int8 `json:"user_id"`
	ApiKeyID          pgtype.Int8 `json:"api_key_id"`
	AnalysisRequestID pgtype.Int8 `json:"analysis_request_id"`
	Type              string      `json:"type"`
	Description       string      `json:"description"`
	IpAddress         *netip.Addr `json:"ip_address"`
	UserAgent         pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.UserID,
		arg.ApiKeyID,
		arg.AnalysisRequestID,
		arg.Type,
		arg.Description,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.AnalysisRequestID,
		&i.Type,
		&i.Description,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, user_id, api_key_id, analysis_request_id, type, description, ip_address, user_agent, created_at FROM audit_events
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiKeyID,
			&i.AnalysisRequestID,
			&i.Type,
			&i.Description,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
