// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgreement = `-- name: CreateAgreement :one
INSERT INTO agreements (
    type, version, document_url, published_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, type, version, document_url, published_at, created_at, updated_at
`

type CreateAgreementParams struct {
	Type        string             `json:"type"`
	Version     string             `json:"version"`
	DocumentUrl string             `json:"document_url"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreateAgreement(ctx context.Context, arg CreateAgreementParams) (Agreement, error) {
	row := q.db.QueryRow(ctx, createAgreement,
		arg.Type,
		arg.Version,
		arg.DocumentUrl,
		arg.PublishedAt,
	)
	var i Agreement
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Version,
		&i.DocumentUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password_hash, role, status, metadata
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, email, password_hash, role, status, metadata, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	Status       string `json:"status"`
	Metadata     []byte `json:"metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUserAgreement = `-- name: CreateUserAgreement :one
INSERT INTO user_agreements (
    user_id, agreement_id
) VALUES (
    $1, $2
) RETURNING id, user_id, agreement_id, accepted_at, created_at, updated_at
`

type CreateUserAgreementParams struct {
	UserID      int64 `json:"user_id"`
	AgreementID int64 `json:"agreement_id"`
}

func (q *Queries) CreateUserAgreement(ctx context.Context, arg CreateUserAgreementParams) (UserAgreement, error) {
	row := q.db.QueryRow(ctx, createUserAgreement, arg.UserID, arg.AgreementID)
	var i UserAgreement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgreementID,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAgreementByID = `-- name: GetAgreementByID :one
SELECT id, type, version, document_url, published_at, created_at, updated_at FROM agreements
WHERE id = $1
`

func (q *Queries) GetAgreementByID(ctx context.Context, id int64) (Agreement, error) {
	row := q.db.QueryRow(ctx, getAgreementByID, id)
	var i Agreement
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Version,
		&i.DocumentUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgreementByTypeAndVersion = `-- name: GetAgreementByTypeAndVersion :one
SELECT id, type, version, document_url, published_at, created_at, updated_at FROM agreements
WHERE type = $1 AND version = $2
`

type GetAgreementByTypeAndVersionParams struct {
	Type    string `json:"type"`
	Version string `json:"version"`
}

func (q *Queries) GetAgreementByTypeAndVersion(ctx context.Context, arg GetAgreementByTypeAndVersionParams) (Agreement, error) {
	row := q.db.QueryRow(ctx, getAgreementByTypeAndVersion, arg.Type, arg.Version)
	var i Agreement
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Version,
		&i.DocumentUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, status, metadata, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, status, metadata, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hasUserAcceptedAgreement = `-- name: HasUserAcceptedAgreement :one
SELECT EXISTS (
    SELECT 1 FROM user_agreements
    WHERE user_id = $1 AND agreement_id = $2
)
`

type HasUserAcceptedAgreementParams struct {
	UserID      int64 `json:"user_id"`
	AgreementID int64 `json:"agreement_id"`
}

func (q *Queries) HasUserAcceptedAgreement(ctx context.Context, arg HasUserAcceptedAgreementParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserAcceptedAgreement, arg.UserID, arg.AgreementID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, password_hash = $3, role = $4, status = $5, metadata = $6, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, role, status, metadata, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	Status       string `json:"status"`
	Metadata     []byte `json:"metadata"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
