// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: analysis.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalysisEngine_Analyze_FullMethodName = "/analysis.AnalysisEngine/Analyze"
)

// AnalysisEngineClient is the client API for AnalysisEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalysisEngineClient interface {
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
}

type analysisEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalysisEngineClient(cc grpc.ClientConnInterface) AnalysisEngineClient {
	return &analysisEngineClient{cc}
}

func (c *analysisEngineClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, AnalysisEngine_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalysisEngineServer is the server API for AnalysisEngine service.
// All implementations must embed UnimplementedAnalysisEngineServer
// for forward compatibility.
type AnalysisEngineServer interface {
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	mustEmbedUnimplementedAnalysisEngineServer()
}

// UnimplementedAnalysisEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalysisEngineServer struct{}

func (UnimplementedAnalysisEngineServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedAnalysisEngineServer) mustEmbedUnimplementedAnalysisEngineServer() {}
func (UnimplementedAnalysisEngineServer) testEmbeddedByValue()                        {}

// UnsafeAnalysisEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalysisEngineServer will
// result in compilation errors.
type UnsafeAnalysisEngineServer interface {
	mustEmbedUnimplementedAnalysisEngineServer()
}

func RegisterAnalysisEngineServer(s grpc.ServiceRegistrar, srv AnalysisEngineServer) {
	// If the following call panics, it indicates UnimplementedAnalysisEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalysisEngine_ServiceDesc, srv)
}

func _AnalysisEngine_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisEngineServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisEngine_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisEngineServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalysisEngine_ServiceDesc is the grpc.ServiceDesc for AnalysisEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalysisEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analysis.AnalysisEngine",
	HandlerType: (*AnalysisEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _AnalysisEngine_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analysis.proto",
}
