from __future__ import annotations

import streamlit as st

# Bump this whenever the terms text changes materially to force re-acceptance.
TERMS_VERSION = "2026-09-02-v3"

TERMS_MARKDOWN = """
**ResumeRanker** analyzes an uploaded resume against an uploaded job description and returns a
structured alignment report. Please read the notice below before uploading any documents.

**Operator**
ResumeRanker is operated by Kishan Thanki. For questions or concerns, contact:
kishanthanki@gmail.com

**How your documents are processed**
- The resume and job description you upload are parsed in memory and analyzed by an AI language
  model to generate your report.
- Resume analysis is performed using a configurable AI language model provider (e.g. OpenAI,
  Anthropic, or another provider). Your uploaded document content is transmitted to that
  provider's API solely to generate the analysis report. Please refer to the applicable
  provider's privacy policy for information on how API data is handled on their end.
- This application does not persist your uploaded files or their extracted text to a database or
  disk. Documents exist only for the duration of your analysis request.
- Operational logs may record non-content metadata (e.g. request ID, token counts, latency,
  error codes) for monitoring and debugging. Resume/job description content is not included in
  these logs.
- No account, login, or persistent user profile is created or required to use this tool.

**Your responsibilities**
- Only upload documents you are authorized to share (your own resume, or a job description you
  have the right to use).
- Avoid including sensitive personal data beyond what is typically found in a resume (e.g. do not
  include government ID numbers, banking details, or medical information).

**Disclaimer**
- Results are generated by an automated model and are provided for informational purposes only.
  They are not a guarantee of accuracy, completeness, or any hiring outcome, and should not be
  the sole basis for any employment decision.
- This service is provided "as is", without warranties of any kind, express or implied. To the
  maximum extent permitted by law, the operator is not liable for any damages arising from use of
  this tool or reliance on its output.

**Governing law**
These terms are governed by the laws of India, without regard to conflict-of-law principles.

By checking the box below and continuing, you confirm you have read this notice, agree to these
terms, and accept the disclaimer above.
"""


def has_accepted_terms() -> bool:
    return (
        bool(st.session_state.get("terms_accepted"))
        and st.session_state.get("terms_accepted_version") == TERMS_VERSION
    )


def render_terms_gate() -> bool:
    """Render the terms/privacy notice gate.

    Returns True once the current session has accepted the current terms version.
    Renders a blocking notice and returns False otherwise, so callers should stop
    rendering the rest of the page when this returns False.
    """
    if has_accepted_terms():
        return True

    st.title("Before you continue")
    st.caption("Please review and accept the notice below to use ResumeRanker.")

    with st.container(border=True):
        st.markdown(TERMS_MARKDOWN)

    agreed = st.checkbox(
        "I have read and agree to the notice above.",
        key="terms_gate_checkbox",
    )
    accept_clicked = st.button(
        "Accept & Continue",
        type="primary",
        disabled=not agreed,
        key="terms_gate_accept",
    )

    if accept_clicked and agreed:
        st.session_state["terms_accepted"] = True
        st.session_state["terms_accepted_version"] = TERMS_VERSION
        st.rerun()

    return False


def render_terms_footer() -> None:
    """Render a read-only expander so users can revisit the notice after accepting."""
    with st.expander("Terms & Privacy Notice"):
        st.markdown(TERMS_MARKDOWN)
