// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredRateLimitCounters = `-- name: DeleteExpiredRateLimitCounters :exec
DELETE FROM rate_limit_counters WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredRateLimitCounters(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRateLimitCounters)
	return err
}

const getRateLimitCounters = `-- name: GetRateLimitCounters :many
SELECT key, count FROM rate_limit_counters
WHERE key = ANY($1::text[]) AND expires_at > NOW()
`

type GetRateLimitCountersRow struct {
	Key   string `json:"key"`
	Count int32  `json:"count"`
}

// Fetches two counter values in one round-trip (minute + day key).
func (q *Queries) GetRateLimitCounters(ctx context.Context, dollar_1 []string) ([]GetRateLimitCountersRow, error) {
	rows, err := q.db.Query(ctx, getRateLimitCounters, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRateLimitCountersRow{}
	for rows.Next() {
		var i GetRateLimitCountersRow
		if err := rows.Scan(&i.Key, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRateLimitCounter = `-- name: UpsertRateLimitCounter :one
INSERT INTO rate_limit_counters (key, count, expires_at)
VALUES ($1, 1, $2)
ON CONFLICT (key) DO UPDATE
    SET count = rate_limit_counters.count + 1,
        -- Refresh expiry only if the incoming expiry is later (prevents shrinking TTL)
        expires_at = GREATEST(rate_limit_counters.expires_at, EXCLUDED.expires_at)
RETURNING count
`

type UpsertRateLimitCounterParams struct {
	Key       string             `json:"key"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Atomically increments counter, creating it if it doesn't exist.
// Returns the new count after increment.
func (q *Queries) UpsertRateLimitCounter(ctx context.Context, arg UpsertRateLimitCounterParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertRateLimitCounter, arg.Key, arg.ExpiresAt)
	var count int32
	err := row.Scan(&count)
	return count, err
}
