// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Agreement struct {
	ID          int64              `json:"id"`
	Type        string             `json:"type"`
	Version     string             `json:"version"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Content     string             `json:"content"`
}

type AnalysisRequest struct {
	ID          int64              `json:"id"`
	RequestID   string             `json:"request_id"`
	UserID      int64              `json:"user_id"`
	ApiKeyID    int64              `json:"api_key_id"`
	Status      string             `json:"status"`
	Error       pgtype.Text        `json:"error"`
	Metadata    []byte             `json:"metadata"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type AnalysisResult struct {
	ID                int64              `json:"id"`
	AnalysisRequestID int64              `json:"analysis_request_id"`
	Model             string             `json:"model"`
	Result            string             `json:"result"`
	PromptTokens      int32              `json:"prompt_tokens"`
	CompletionTokens  int32              `json:"completion_tokens"`
	TotalTokens       int32              `json:"total_tokens"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type ApiKey struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	Name              string             `json:"name"`
	KeySelector       string             `json:"key_selector"`
	KeyHash           string             `json:"key_hash"`
	Status            string             `json:"status"`
	TokenQuota        int64              `json:"token_quota"`
	TokensUsed        int64              `json:"tokens_used"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	KeyPrefix         string             `json:"key_prefix"`
	RequestsPerMinute int32              `json:"requests_per_minute"`
	RequestsPerDay    int32              `json:"requests_per_day"`
}

type AuditEvent struct {
	ID                int64              `json:"id"`
	UserID            pgtype.Int8        `json:"user_id"`
	ApiKeyID          pgtype.Int8        `json:"api_key_id"`
	AnalysisRequestID pgtype.Int8        `json:"analysis_request_id"`
	Type              string             `json:"type"`
	Description       string             `json:"description"`
	IpAddress         *netip.Addr        `json:"ip_address"`
	UserAgent         pgtype.Text        `json:"user_agent"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                     int64              `json:"id"`
	Email                  string             `json:"email"`
	PasswordHash           string             `json:"password_hash"`
	Role                   string             `json:"role"`
	Status                 string             `json:"status"`
	Metadata               []byte             `json:"metadata"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	IsVerified             bool               `json:"is_verified"`
	VerificationToken      pgtype.Text        `json:"verification_token"`
	VerificationExpiresAt  pgtype.Timestamptz `json:"verification_expires_at"`
	PasswordResetToken     pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpiresAt pgtype.Timestamptz `json:"password_reset_expires_at"`
}

type UserAgreement struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	AgreementID int64              `json:"agreement_id"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
