// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnalysisRequest = `-- name: CreateAnalysisRequest :one
INSERT INTO analysis_requests (
    request_id, user_id, api_key_id, status, error, metadata, started_at, completed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, request_id, user_id, api_key_id, status, error, metadata, started_at, completed_at, created_at, updated_at, deleted_at
`

type CreateAnalysisRequestParams struct {
	RequestID   string             `json:"request_id"`
	UserID      int64              `json:"user_id"`
	ApiKeyID    int64              `json:"api_key_id"`
	Status      string             `json:"status"`
	Error       pgtype.Text        `json:"error"`
	Metadata    []byte             `json:"metadata"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateAnalysisRequest(ctx context.Context, arg CreateAnalysisRequestParams) (AnalysisRequest, error) {
	row := q.db.QueryRow(ctx, createAnalysisRequest,
		arg.RequestID,
		arg.UserID,
		arg.ApiKeyID,
		arg.Status,
		arg.Error,
		arg.Metadata,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i AnalysisRequest
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.Status,
		&i.Error,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAnalysisResult = `-- name: CreateAnalysisResult :one
INSERT INTO analysis_results (
    analysis_request_id, model, result, prompt_tokens, completion_tokens, total_tokens
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, analysis_request_id, model, result, prompt_tokens, completion_tokens, total_tokens, created_at, updated_at, deleted_at
`

type CreateAnalysisResultParams struct {
	AnalysisRequestID int64  `json:"analysis_request_id"`
	Model             string `json:"model"`
	Result            string `json:"result"`
	PromptTokens      int32  `json:"prompt_tokens"`
	CompletionTokens  int32  `json:"completion_tokens"`
	TotalTokens       int32  `json:"total_tokens"`
}

func (q *Queries) CreateAnalysisResult(ctx context.Context, arg CreateAnalysisResultParams) (AnalysisResult, error) {
	row := q.db.QueryRow(ctx, createAnalysisResult,
		arg.AnalysisRequestID,
		arg.Model,
		arg.Result,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
	)
	var i AnalysisResult
	err := row.Scan(
		&i.ID,
		&i.AnalysisRequestID,
		&i.Model,
		&i.Result,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAnalysisRequest = `-- name: DeleteAnalysisRequest :exec
UPDATE analysis_requests
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteAnalysisRequest(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAnalysisRequest, id)
	return err
}

const deleteAnalysisResult = `-- name: DeleteAnalysisResult :exec
UPDATE analysis_results
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteAnalysisResult(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAnalysisResult, id)
	return err
}

const getAnalysisRequestByID = `-- name: GetAnalysisRequestByID :one
SELECT id, request_id, user_id, api_key_id, status, error, metadata, started_at, completed_at, created_at, updated_at, deleted_at FROM analysis_requests
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAnalysisRequestByID(ctx context.Context, id int64) (AnalysisRequest, error) {
	row := q.db.QueryRow(ctx, getAnalysisRequestByID, id)
	var i AnalysisRequest
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.Status,
		&i.Error,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAnalysisResultByRequestID = `-- name: GetAnalysisResultByRequestID :one
SELECT id, analysis_request_id, model, result, prompt_tokens, completion_tokens, total_tokens, created_at, updated_at, deleted_at FROM analysis_results
WHERE analysis_request_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAnalysisResultByRequestID(ctx context.Context, analysisRequestID int64) (AnalysisResult, error) {
	row := q.db.QueryRow(ctx, getAnalysisResultByRequestID, analysisRequestID)
	var i AnalysisResult
	err := row.Scan(
		&i.ID,
		&i.AnalysisRequestID,
		&i.Model,
		&i.Result,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAnalysisRequestsByUserID = `-- name: ListAnalysisRequestsByUserID :many
SELECT id, request_id, user_id, api_key_id, status, error, metadata, started_at, completed_at, created_at, updated_at, deleted_at FROM analysis_requests
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAnalysisRequestsByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAnalysisRequestsByUserID(ctx context.Context, arg ListAnalysisRequestsByUserIDParams) ([]AnalysisRequest, error) {
	rows, err := q.db.Query(ctx, listAnalysisRequestsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalysisRequest{}
	for rows.Next() {
		var i AnalysisRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Status,
			&i.Error,
			&i.Metadata,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnalysisRequest = `-- name: UpdateAnalysisRequest :one
UPDATE analysis_requests
SET status = $2, error = $3, metadata = $4, started_at = $5, completed_at = $6, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, request_id, user_id, api_key_id, status, error, metadata, started_at, completed_at, created_at, updated_at, deleted_at
`

type UpdateAnalysisRequestParams struct {
	ID          int64              `json:"id"`
	Status      string             `json:"status"`
	Error       pgtype.Text        `json:"error"`
	Metadata    []byte             `json:"metadata"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateAnalysisRequest(ctx context.Context, arg UpdateAnalysisRequestParams) (AnalysisRequest, error) {
	row := q.db.QueryRow(ctx, updateAnalysisRequest,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.Metadata,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i AnalysisRequest
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ApiKeyID,
		&i.Status,
		&i.Error,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
