"""add audit_events table

Revision ID: 524f3d7eb66b
Revises: fd88f1d9968d
Create Date: 2026-05-24 17:04:27.240853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '524f3d7eb66b'
down_revision: Union[str, None] = 'fd88f1d9968d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_email_created_at', 'audit_events', ['email', 'created_at'], unique=False)
    op.create_index('ix_audit_events_type_created_at', 'audit_events', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_audit_events_user_id_created_at', 'audit_events', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_events_user_id_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_type_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_email_created_at', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
