"""add policy acceptance fields

Revision ID: fd88f1d9968d
Revises: b00671535e6c
Create Date: 2026-05-19 11:59:20.226554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd88f1d9968d'
down_revision: Union[str, None] = 'b00671535e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add the columns. All nullable so the migration is non-blocking; the
    # backfill below stamps existing users as pre-policy. New users
    # signing up after this migration will populate the columns via the
    # click-wrap acceptance flow in /auth.
    op.add_column('magic_links', sa.Column('accepted_policy_version', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('accepted_policy_version', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('accepted_policy_at', sa.DateTime(timezone=True), nullable=True))

    # Backfill existing users as having accepted a "pre-policy" version,
    # so existing sessions remain valid and no one is interrupted on next
    # sign-in. The literal version string captures when these users were
    # grandfathered. Anyone added after this migration goes through the
    # real click-wrap acceptance flow.
    op.execute(
        "UPDATE users "
        "SET accepted_policy_version = 'pre-policy-2026-05-19', "
        "    accepted_policy_at = NOW() "
        "WHERE accepted_policy_version IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accepted_policy_at')
    op.drop_column('users', 'accepted_policy_version')
    op.drop_column('magic_links', 'accepted_policy_version')
    # ### end Alembic commands ###
