# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\x08\x61nalysis\"U\n\x0e\x41nalyzeRequest\x12\x12\n\nresume_pdf\x18\x01 \x01(\x0c\x12\x1b\n\x13job_description_pdf\x18\x02 \x01(\x0c\x12\x12\n\nrequest_id\x18\x03 \x01(\t\"\xa0\x01\n\x0f\x41nalyzeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x13\n\x0bresult_json\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t\x12\x14\n\x0cinput_tokens\x18\x05 \x01(\r\x12\x15\n\routput_tokens\x18\x06 \x01(\r\x12\x14\n\x0ctotal_tokens\x18\x07 \x01(\r2P\n\x0e\x41nalysisEngine\x12>\n\x07\x41nalyze\x12\x18.analysis.AnalyzeRequest\x1a\x19.analysis.AnalyzeResponseB@Z>github.com/kishan-thanki/resumeranker/api/internal/analysis/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/kishan-thanki/resumeranker/api/internal/analysis/pb'
  _globals['_ANALYZEREQUEST']._serialized_start=28
  _globals['_ANALYZEREQUEST']._serialized_end=113
  _globals['_ANALYZERESPONSE']._serialized_start=116
  _globals['_ANALYZERESPONSE']._serialized_end=276
  _globals['_ANALYSISENGINE']._serialized_start=278
  _globals['_ANALYSISENGINE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
