// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    user_id, name, key_selector, key_hash, status, token_quota, tokens_used, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_id, name, key_selector, key_hash, status, token_quota, tokens_used, expires_at, last_used_at, created_at, updated_at, deleted_at
`

type CreateAPIKeyParams struct {
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	KeySelector string             `json:"key_selector"`
	KeyHash     string             `json:"key_hash"`
	Status      string             `json:"status"`
	TokenQuota  int64              `json:"token_quota"`
	TokensUsed  int64              `json:"tokens_used"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeySelector,
		arg.KeyHash,
		arg.Status,
		arg.TokenQuota,
		arg.TokensUsed,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeySelector,
		&i.KeyHash,
		&i.Status,
		&i.TokenQuota,
		&i.TokensUsed,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
UPDATE api_keys
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, id)
	return err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, user_id, name, key_selector, key_hash, status, token_quota, tokens_used, expires_at, last_used_at, created_at, updated_at, deleted_at FROM api_keys
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id int64) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeySelector,
		&i.KeyHash,
		&i.Status,
		&i.TokenQuota,
		&i.TokensUsed,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAPIKeyBySelector = `-- name: GetAPIKeyBySelector :one
SELECT id, user_id, name, key_selector, key_hash, status, token_quota, tokens_used, expires_at, last_used_at, created_at, updated_at, deleted_at FROM api_keys
WHERE key_selector = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAPIKeyBySelector(ctx context.Context, keySelector string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyBySelector, keySelector)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeySelector,
		&i.KeyHash,
		&i.Status,
		&i.TokenQuota,
		&i.TokensUsed,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAPIKeysByUserID = `-- name: ListAPIKeysByUserID :many
SELECT id, user_id, name, key_selector, key_hash, status, token_quota, tokens_used, expires_at, last_used_at, created_at, updated_at, deleted_at FROM api_keys
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUserID(ctx context.Context, userID int64) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeySelector,
			&i.KeyHash,
			&i.Status,
			&i.TokenQuota,
			&i.TokensUsed,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKey = `-- name: UpdateAPIKey :one
UPDATE api_keys
SET status = $2, token_quota = $3, tokens_used = $4, expires_at = $5, last_used_at = $6, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, name, key_selector, key_hash, status, token_quota, tokens_used, expires_at, last_used_at, created_at, updated_at, deleted_at
`

type UpdateAPIKeyParams struct {
	ID         int64              `json:"id"`
	Status     string             `json:"status"`
	TokenQuota int64              `json:"token_quota"`
	TokensUsed int64              `json:"tokens_used"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateAPIKey,
		arg.ID,
		arg.Status,
		arg.TokenQuota,
		arg.TokensUsed,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeySelector,
		&i.KeyHash,
		&i.Status,
		&i.TokenQuota,
		&i.TokensUsed,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
