"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import analysis_pb2 as _analysis_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AnalysisEngineStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> AnalysisEngineAsyncStub: ...
    Analyze: _grpc.UnaryUnaryMultiCallable[_analysis_pb2.AnalyzeRequest, _analysis_pb2.AnalyzeResponse]

@_typing.type_check_only
class AnalysisEngineAsyncStub(AnalysisEngineStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Analyze: _aio.UnaryUnaryMultiCallable[_analysis_pb2.AnalyzeRequest, _analysis_pb2.AnalyzeResponse]  # type: ignore[assignment]

class AnalysisEngineServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Analyze(
        self,
        request: _analysis_pb2.AnalyzeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_analysis_pb2.AnalyzeResponse, _abc.Awaitable[_analysis_pb2.AnalyzeResponse]]: ...

def add_AnalysisEngineServicer_to_server(servicer: AnalysisEngineServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
