"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AnalyzeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESUME_PDF_FIELD_NUMBER: _builtins.int
    JOB_DESCRIPTION_PDF_FIELD_NUMBER: _builtins.int
    REQUEST_ID_FIELD_NUMBER: _builtins.int
    resume_pdf: _builtins.bytes
    job_description_pdf: _builtins.bytes
    request_id: _builtins.str
    def __init__(
        self,
        *,
        resume_pdf: _builtins.bytes = ...,
        job_description_pdf: _builtins.bytes = ...,
        request_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job_description_pdf", b"job_description_pdf", "request_id", b"request_id", "resume_pdf", b"resume_pdf"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AnalyzeRequest: _TypeAlias = AnalyzeRequest  # noqa: Y015

@_typing.final
class AnalyzeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: _builtins.int
    RESULT_JSON_FIELD_NUMBER: _builtins.int
    MODEL_FIELD_NUMBER: _builtins.int
    INPUT_TOKENS_FIELD_NUMBER: _builtins.int
    OUTPUT_TOKENS_FIELD_NUMBER: _builtins.int
    TOTAL_TOKENS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error_message: _builtins.str
    result_json: _builtins.str
    model: _builtins.str
    input_tokens: _builtins.int
    output_tokens: _builtins.int
    total_tokens: _builtins.int
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error_message: _builtins.str = ...,
        result_json: _builtins.str = ...,
        model: _builtins.str = ...,
        input_tokens: _builtins.int = ...,
        output_tokens: _builtins.int = ...,
        total_tokens: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error_message", b"error_message", "input_tokens", b"input_tokens", "model", b"model", "output_tokens", b"output_tokens", "result_json", b"result_json", "success", b"success", "total_tokens", b"total_tokens"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AnalyzeResponse: _TypeAlias = AnalyzeResponse  # noqa: Y015
